### PR TITLE
x/tokenfactory

### LINKED ISSUE #11: x/TokenFactory module
Follow osmosis way of denoms & such

Mix best of osmosis & CW20 messages

Ban ueve / eve creation?

- Way to add --flags to init command? To specify metadata

- don’t allow /‘s in the subdenom

### PR DESCRIPTION
**Pull request by Reecepbcups**
close #11 

I still don't know how to generate proto, so uses their namespace still for now via REST / RPC
http://localhost:1317/clockworkgr/tokenfactory/tokenfactory/denom

### CODE REVIEW

**Comment by Reecepbcups** [comment]
I keep getting a `could not find protoc plugin for name grpc-gateway` error from buf.gen.gogo.yaml. Even though I am using `github.com/grpc-ecosystem/grpc-gateway v1.16.0` like craft in my go.mod.

I have my go path setup correctly & protoc-gen-go-gprc installed
image

What am I missing here @vuong177 ?

**Comment by faddat** [comment]
hmmmm @nghuyenthevinh2000 is our finest with protobufs.  Also, once this is complete it makes a ton of sense to take the same work and PR it to cosmwasm per:

* https://github.com/CosmWasm/wasmd/issues/911

many folks feel that tokenfactory is "the right way" and I'm one of them

**Comment by vuong177** [comment]
@Reecepbcups you can try
```
$ go install \
    github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway \
    github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2 \
    google.golang.org/protobuf/cmd/protoc-gen-go \
    google.golang.org/grpc/cmd/protoc-gen-go-grpc

```

**Comment by Reecepbcups** [comment]
> @Reecepbcups you can try
> 
> ```
>  go install \
>     github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway \
>     github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2 \
>     google.golang.org/protobuf/cmd/protoc-gen-go \
>     google.golang.org/grpc/cmd/protoc-gen-go-grpc
> ```

yea I did that & finally got it from some cosmos-sdk issue / PR
issue now is that it still has other endpoint & not the updated one, so thats my next task to figure out thx

**Comment by Reecepbcups** [comment]
> hmmmm @nghuyenthevinh2000 is our finest with protobufs. Also, once this is complete it makes a ton of sense to take the same work and PR it to cosmwasm per:
> 
> * [Add tokenfactory module CosmWasm/wasmd#911](https://github.com/CosmWasm/wasmd/issues/911)
> 
> many folks feel that tokenfactory is "the right way" and I'm one of them

I agree with it as well, CW20 kinda meh when Cosmos bank is already so good

I feel I should convert it to be more like osmosis with the `factory/address/denom` most likely, will continue to look into as best approach

**Comment by faddat** [comment]
I think I support doing it exactly the osmosis-way.

Hope that we don't end up finding that this blocks us from using sdk v0.46.* due to something related to:

https://github.com/CosmWasm/wasmd/issues/941

It might be worth pinging @fadeev from the ignite cli / starport team.  as we can think of eve, structurally as "slim craft".  She may be usable without too many changes as a template, as long as we can come to agreement on the cmd folder contents -- I do not want to wrap cmd the way that the ignite cli historically has.

**Comment by nghuyenthevinh2000** [comment]
@Reecepbcups 
For proto generation, try to use this docker. It has all the protoc-gen binaries installed. No more hassle of figuring out the correct protoc-gen binaries to install.

https://github.com/cosmos/cosmos-sdk/blob/main/Makefile#L395 

tendermintdev/sdk-proto-gen:v0.7

**Comment by Reecepbcups** [comment]
> I think I support doing it exactly the osmosis-way.
> 
> Hope that we don't end up finding that this blocks us from using sdk v0.46.* due to something related to:
> 
> [CosmWasm/wasmd#941](https://github.com/CosmWasm/wasmd/issues/941)
> 
> It might be worth pinging @fadeev from the ignite cli / starport team. as we can think of eve, structurally as "slim craft". She may be usable without too many changes as a template, as long as we can come to agreement on the cmd folder contents -- I do not want to wrap cmd the way that the ignite cli historically has.

So  as I have looked into this, osmosis uses a lot of their SDK related things for testing & in their modified bankKeeper for denom data.
Also, has some really weird features like **burn denom from any account**

I took a more CW20 approach given that is what the factory is for, where the admin can only mint new tokens to an account, not modify others balances

**Comment by faddat** [comment]
Propose that we revert the last commit then merge?

**Comment by Reecepbcups** [comment]
> Propose that we revert the last commit then merge?

yea thanks Ill work on that later, need to clean up a few functions & will push on main soon
Definitely a need later so CW can use native denoms instead of CW20 (which are bleh for queries)

Have to do it the factory/addr/{denom} way so namespaces done merge
else someone could mint ueve & mint to anyone, just found that bug :P

**Pull request merged**
