### PR TITLE
x/globalfee

### LINKED ISSUE #22: global fees
See Gaia -

[github.com/cosmos/gaia](https://github.com/cosmos/gaia/tree/main/x/globalfee)

Maybe do just how they did, give credit to them for the 46 converty and to tgrade for origination.  I think this is a very desirable feature.

We may not need to copy Gaia's x folder though.  Might just be able to smoothly import it. 

If we are copying Gaia at all, it might actually make sense to have a look at her test suite.  Let's get eve very sharp, pointed and deterministic.

### PR DESCRIPTION
**Pull request by Reecepbcups**
Would close #22 

- eved q globalfee minimum-gas-prices
```
only returns an array []
reason: can't make proto-gen because of:

Generating Protobuf files
Generating gogo proto code
Failure: buf.build/cosmos/cosmos-sdk:233f8f38503f47ada7a7eca116b84303: does not exist
make: *** [Makefile:96: proto-gen] Error 1
```

- removed ante test since its gaia specific

### CODE REVIEW

**Comment by faddat** [comment]
Really awesome. On vacation for the next couple of days but I might clean this up some.

**Comment by Reecepbcups** [comment]
`Error: rpc error: code = Unknown desc = unknown query path: unknown request`
for query now

**Comment by faddat** [comment]
let me guess:

the testnet runs fine on your computer-- but dies here?

**Comment by Reecepbcups** [comment]
> let me guess:
> 
> the testnet runs fine on your computer-- but dies here?

yes, testnet works but dies when trying to query. Really think its bc of the Proto path. Buf wont let me `buf mod update` and its solution to fix the issue is the same command. So can't compile and proto again :(
so Im completely stuck for a bit until i can figure that out

**Comment by faddat** [comment]
try 

make proto-update-deps

I took some Makefile from ibc-go v5.0.0

**Comment by Reecepbcups** [comment]
> make proto-update-deps

already tried everything found in teh make file earlier + changed between versions from v0.2 -> v0.7 no luck
```
(0) reece@pbcupsd [~/Desktop/Programming/Go/eve]
(x/globalfee) -> $ make proto-update-deps
/bin/sh: line 1: third_party/proto/cosmos/upgrade/v1beta1/upgrade.proto: No such file or directory
make: *** [Makefile:146: proto-update-deps] Error 1
```

I guess I spend the next few days learning all proto / buf from scratch & see if I can figure it out

**Comment by faddat** [comment]
I got to the same place....

**Comment by faddat** [comment]
Reece, I have the proto issues resolved. 

Buf gen and such should work now.

**Comment by faddat** [comment]
I can run this branch on my computer.

**Comment by Reecepbcups** [comment]
Thanks will try this tomorrow for the proto

Also, that "unneeded" line commit above, I put to ensure custom future types work & not just the base Globalfees

Testnet file is a pain though. Honestly may be simpler to use the ./test_node.sh script & docker-compose it to connect 2 eve nodes

**Comment by faddat** [comment]
you're kinda right about this man.

**Comment by Reecepbcups** [comment]
> you're kinda right about this man.

done :)

**Pull request merged**
