### PR TITLE
Cosmwasm + 'IBC v5" + Upgrade Handler

### LINKED ISSUE #9: CosmWasm
Eve needs some hot CW action if she's ever to get with her beloved Juno

### PR DESCRIPTION
**Pull request by Reecepbcups**
closes #9 

CosmWasm 0.28 + IBC v5 (v4 fork)

### CODE REVIEW

**Comment by faddat** [comment]
nice!

**Comment by faddat** [comment]
just need to fix some tests -- basically she doesn't know who she is again :D

**Comment by faddat** [comment]
bet this passes...

**Comment by Reecepbcups** [comment]
> bet this passes...

that would be very nice

**Comment by Reecepbcups** [comment]
Tested wasm with a 721, init, execute, and query no issues

**Comment by Reecepbcups** [comment]
As you're busy with the Hetzner situation, going to forge merge now & can re-review later.

**Pull request merged**
